### PR TITLE
Initial project architecture draft

### PR DESCRIPTION
**Pull request by mavvkel**
The general architecture of the project is added. **Only the RMS app is actually supplied with the concrete classes mentioned in the specification.** If this approach is correct, the rest of the classes of RMS have to be supplied & the same has to be done for CMS and DMS apps. Check it out and let me know if you have any doubts.

### CODE REVIEW

**Review by olaf-duda — APPROVED** [review]
I approve the changes

**Comment by Bartkosa** [comment]
Approved

**Review by Bartkosa — APPROVED** [review]
Approved

**Comment by AjgorBzd** [comment]
fajny program

**Review by AjgorBzd — COMMENTED** [review]
superancko

**Pull request merged**
